#exemplo da implementação de um load balancer com o nghttpx em docker
version: '3.8'

services:
# Load balancer
  lb:
    container_name: my_lb
    image: jrofurtado/nghttpx-autoreload-with-healthcheck:1.0.0
    environment:
      PARAMS: '
        -f"*,80;no-tls" 
        -b"foa,80;;dns;"
        -f"*,8888;no-tls" 
        -b"fob,80;;dns;"'
    ports:
      - 80:80
      - 8888:80
    volumes:
      - lb-data:/volume
    networks:
      - lb-nw
      - fo-nw


#web server A
  foa:
    container_name: my_foa
    image: nginx:latest
    networks:
      - fo-nw
      - lb-nw

#web server B 
  fob:
    container_name: my_fob
    image: nginx:latest
    networks:
      - fo-nw
      - lb-nw


networks:
  lb-nw:
  fo-nw:

volumes:
  lb-data:
    external: false




