version: '3.8'

services:
# Load balancer
  lb:
    container_name: my_lb
    image: jrofurtado/nghttpx-autoreload-with-healthcheck:1.0.0
    environment:
      PARAMS: '
        -f"*,80;no-tls" 
        -b"fo,8888;;dns;"'
    ports:
      - 80:80
    volumes:
      - lb-data:/volume
    networks:
      - lb-nw
      - fo-nw

  fo:
    container_name: my_fo
    image: nginx:latest
    networks:
      - fo-nw
      - lb-nw

networks:
  lb-nw:
  fo-nw:

volumes:
  lb-data:
    external: false




